name: C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install cmake zip tree ccache -y 

      - name: Install (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake ccache -y

      - name: Short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Show project tree
        run: tree -L 3

      - name: Cache ccache
        uses: actions/cache@v4
        with:
            path: ~/.ccache
            key: ccache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure
        shell: bash
        run: |
            cmake -S . -B build \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DAPP_VERSION=build-${{ github.ref_name }}-${{ env.SHORT_SHA }} \
            -DGIT_HASH=${{ github.sha }} \
            -DBUILD_OS=${{ runner.os }} \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Show ccache stats
        run: ccache -s

      - name: Prepare Linux binary
        if: runner.os == 'Linux'
        run: |
            mkdir dist
            cp build/my_app dist/my_app-${{ github.ref_name }}-linux

      - name: Prepare Windows binary
        if: runner.os == 'Windows'
        run: |
            mkdir dist
            copy build\Release\my_app.exe dist\my_app-${{ github.ref_name }}-windows.exe

      - name: Debug files
        run: |
            pwd
        
      - name: Show project tree
        run: tree -L 3

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
            name: binaries-${{ runner.os }}
            path: dist/*

      - name: Show project tree
        run: tree -L 3
