name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y cmake zip

      - name: Install CMake (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake -y

      - name: Configure
        run: |
            cmake -S . -B build \
            -DAPP_VERSION=${{ github.ref_name }} \
            -DGIT_HASH=${{ github.sha }} \
            -DBUILD_OS=${{ runner.os }} \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Linux binary
        if: runner.os == 'Linux'
        run: |
            cp build/my_app my_app-${{ github.ref_name }}-linux
            zip my_app-${{ github.ref_name }}-linux.zip my_app-${{ github.ref_name }}-linux
            
      - name: Package Windows binary
        if: runner.os == 'Windows'
        run: |
            copy build\Release\my_app.exe my_app-${{ github.ref_name }}-windows.exe
            powershell Compress-Archive my_app-${{ github.ref_name }}-windows.exe my_app-${{ github.ref_name }}-windows.zip

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            my_app-${{ github.ref_name }}-linux.zip
            my_app-${{ github.ref_name }}-windows.zip
