name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install cmake zip tree ccache -y

      - name: Install (Windows)
        if: runner.os == 'Windows'
        run: choco install cmake ccache -y

      - name: Cache ccache
        uses: actions/cache@v4
        with:
            path: ~/.ccache
            key: ccache-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure
        shell: bash
        run: |
            cmake -S . -B build \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -DAPP_VERSION=${{ github.ref_name }} \
            -DGIT_HASH=${{ github.sha }} \
            -DBUILD_OS=${{ runner.os }} \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Show ccache stats
        run: ccache -s

      - name: Show project tree
        run: tree -L 3

      - name: Package Linux binary
        if: runner.os == 'Linux'
        run: |
            cp build/my_app my_app-${{ github.ref_name }}-linux
            zip my_app-${{ github.ref_name }}-linux.zip my_app-${{ github.ref_name }}-linux
            
      - name: Package Windows binary
        if: runner.os == 'Windows'
        run: |
            copy build\Release\my_app.exe my_app-${{ github.ref_name }}-windows.exe
            powershell Compress-Archive my_app-${{ github.ref_name }}-windows.exe my_app-${{ github.ref_name }}-windows.zip

      - name: Show project tree
        run: tree -L 3

      - name: Extract changelog
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME}
          awk "/^## ${VERSION}/{flag=1;next}/^## v/{flag=0}flag" CHANGELOG.md > RELEASE.md

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            my_app-${{ github.ref_name }}-linux.zip
            my_app-${{ github.ref_name }}-windows.zip
          body_path: RELEASE.md
